In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
pip install biopython

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 26.9 MB/s eta 0:00:00


In [ ]:
from Bio import pairwise2
from Bio.pairwise2 import format_alignment
from Bio import SeqIO
from Bio import pairwise2
import numpy as np
import pandas as pd

### Calculating Smith-Waterman alignment score
def smith_waterman_alignment_score(seq1, seq2, match_score=2, mismatch_penalty=-1, gap_open_penalty=-1, gap_extend_penalty=-1):

    # The pairwise2.align.localms() function for local sequence alignment
    alignments = pairwise2.align.localms(seq1, seq2, match_score, mismatch_penalty, gap_open_penalty, gap_extend_penalty)
    best_alignment = max(alignments, key = lambda x: x.score)

    return best_alignment.score       #Return the best alignment

/usr/local/lib/python3.10/dist-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(


In [ ]:
### Pair-wise similarity matrix
def get_similarity_matrix(sequences, num_sequences):

  similarity_matrix = np.zeros((num_sequences,num_sequences))
  for i in range(num_sequences):
      for j in range(i, num_sequences):
          seq1 = sequences[i].seq
          seq2 = sequences[j].seq
          alignment_score = smith_waterman_alignment_score(seq1, seq2)

          # Assume symmetry
          similarity_matrix[i][j] = similarity_matrix[j][i] = alignment_score

  return similarity_matrix

In [ ]:
### Importing the FASTA file
fasta_file_path = "/content/drive/MyDrive/Colab Notebooks/LSD/sequences.fasta"
fasta_iterator = SeqIO.parse(fasta_file_path, "fasta")
sequences = list(fasta_iterator)
sorted_seq = sorted(sequences, key=lambda sequence: sequence.seq)
top100_seq = sorted_seq[0:100]
num_sequences = len(top100_seq)

### Pair-wise similarity matrix
similarity_matrix = get_similarity_matrix(top100_seq, num_sequences)

## Print the similarity matrix
print(similarity_matrix)

[[ 96.   9.   6. ...   6.   9.   4.]
 [  9. 160.   6. ...   8.   8.   5.]
 [  6.   6.  90. ...   6.   6.   4.]
 ...
 [  6.   8.   6. ... 166.   8.   5.]
 [  9.   8.   6. ...   8. 308.   7.]
 [  4.   5.   4. ...   5.   7.  20.]]
